public class GasCar extends Car {
  public Integer thankCapacity;
  public GasCar(String model, Decimal price, Integer thankCapacity) {
    super(model, price);
    this.thankCapacity = thankCapacity;
  }
  /**
   * Create overriden version  of the drive method to print different messege
   *
   */
  public override void drive() {
    System.debug('Car' + this.model + 'is driving on gas');
  }

       /**
     * Add a method called fillupGas 
     * accept no param , return nothing 
     * simply print out -- CarModelHere is filling up Gas
     */
    public void fillupGas(){
        System.debug( this.model + ' is filling up Gas'); 
   
}
}