//public is the key word to define access level 
//know as access modifier, there are couple of them we will learn later
////class: indicate this is a class
//phone:indentifier, the name of the class
//{any code need to go in there, can not go outside}
// The moment the class exist it can be a data type
//// meaning, you can cretae a variable of that Type
//you can create a new instance (object) of that type and assign the variable
// and much more
public class Phone {
// a phone has below 
// attributes or characteristics
// brand, price, memorysize
// instance variable | field 

    
 public String brand;
 public Decimal price;
 public Integer memorySize;
    

}